spring:
  elasticsearch:
    rest:
      uris: http://43.139.118.53:9200

elasticsearch:
  nodes:
    - {ip: '43.139.118.53',port: 9200}
  connectTimeout: 60000
  socketTimeout: 60000
  connectionRequestTimeout: 1500
  maxConnectPerRoute: 200
  maxConnectTotal: 200
  username:
  password:
